### ISSUE TITLE
Fix Tests

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/PowerModelsGMD.jl#42]
@bluejuniper, the tests should be updated so that they are passing on CI (e.g. https://travis-ci.org/lanl-ansi/PowerModelsGMD.jl).

Ideally the tests should be optimized to run faster as well.

CC @rb004f

**Comment by bluejuniper** [comment]
Most of the test time is taken by the OTS formulation. I seem to recall that some packages have a full_test option time time consuming stuff, would that make sense here?

**Comment by ccoffrin** [comment]
That is a reasonable quick fix, but a better solution is to build some very small networks that can be used for testing and remove the larger cases.

**Comment by ccoffrin** [comment]
The most critical issue at this time is that some tests are not passing on master.

**Comment by bluejuniper** [comment]
Looks like the tests are passing now, it's the docs building that is failing. This is not surprising since I haven't made documentation outside the README.

**Comment by ccoffrin** [comment]
Fantastic!  I'll fix the doc building setup so it's ready to go.

**Comment by ccoffrin** [comment]
Docs are building and hosted here, https://lanl-ansi.github.io/PowerModelsGMD.jl/latest/

@bluejuniper, @rb004f
