### ISSUE TITLE
Move away from modified KCL constraint for GMD transformer Qloss

### ISSUE THREAD

**Issue by adammate** [lanl-ansi/PowerModelsGMD.jl#63]
use "special" loads instead of modified KCL constraint for GMD transformer Qloss? H. Zhu and T. J. Overbye, “Blocking Device Placement for Mitigating the Effects of Geomagnetically Induced Currents,” IEEE Transactions on Power Systems, vol. 30, Art. no. 4, Jul. 2015.

**Comment by jtabarez** [comment]
We've decided against this because if this constraint causes the problem to be infeasible it is because the system is in a truly inoperable state
