### ISSUE TITLE
Ieff calculation for autotransformers is wrong

### ISSUE THREAD

**Issue by bluejuniper** [lanl-ansi/PowerModelsGMD.jl#69]
Use (15) from K. Zheng et al., “Effects of System Characteristics on Geomagnetically Induced Currents,” IEEE Transactions on Power Delivery, vol. 29, no. 2, pp. 890–898, Apr. 2014, doi: 10.1109/TPWRD.2013.2281191.

**Comment by jtabarez** [comment]
The coupled constraint is missing

**Comment by jtabarez** [comment]
Looks to be fixed in jose-develop
